const https = require('https');
const fs = require('fs');
const path = require('path');

function get(url, headers = {}) {
  return new Promise((resolve, reject) => {
    const options = {
      headers: {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
        'Accept': 'application/json',
        ...headers
      },
      timeout: 20000
    };
    const req = https.get(url, options, (res) => {
      if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
        return get(res.headers.location, headers).then(resolve).catch(reject);
      }
      const chunks = [];
      res.on('data', chunk => chunks.push(chunk));
      res.on('end', () => resolve({ status: res.statusCode, body: Buffer.concat(chunks).toString() }));
    });
    req.on('error', reject);
    req.on('timeout', () => { req.destroy(); reject(new Error('Timeout')); });
  });
}

function sleep(ms) { return new Promise(r => setTimeout(r, ms)); }

function updateCSV(filepath, value) {
  const today = new Date().toISOString().split('T')[0];
  const header = 'Date,Time,Open,High,Low,Close,Volume';
  const row = `${today},00:00,${value},${value},${value},${value},0`;

  fs.mkdirSync(path.dirname(filepath), { recursive: true });

  let lines = [];
  if (fs.existsSync(filepath)) {
    lines = fs.readFileSync(filepath, 'utf8').trim().split('\n').filter(Boolean);
  }
  if (!lines.length || !lines[0].startsWith('Date')) lines.unshift(header);

  const idx = lines.findIndex(l => l.startsWith(today));
  if (idx >= 0) lines[idx] = row;
  else lines.push(row);

  fs.writeFileSync(filepath, lines.join('\n') + '\n');
  console.log(`✅ ${filepath} → ${value}`);
}

function generatePineScript() {
  // Read both CSVs
  const fiiLines = fs.readFileSync('data/FII_NET/data.csv', 'utf8')
    .trim().split('\n').filter(Boolean)
    .filter(l => !l.startsWith('Date'));

  const diiLines = fs.readFileSync('data/DII_NET/data.csv', 'utf8')
    .trim().split('\n').filter(Boolean)
    .filter(l => !l.startsWith('Date'));

  // Build lookup maps keyed by date
  const fiiMap = {};
  for (const line of fiiLines) {
    const [date, , , , , close] = line.split(',');
    fiiMap[date] = parseFloat(close);
  }
  const diiMap = {};
  for (const line of diiLines) {
    const [date, , , , , close] = line.split(',');
    diiMap[date] = parseFloat(close);
  }

  // Union of all dates, sorted
  const allDates = [...new Set([...Object.keys(fiiMap), ...Object.keys(diiMap)])].sort();

  // Build switch arms
  const fiiArms = allDates
    .filter(d => fiiMap[d] !== undefined)
    .map(d => `    "${d}" => ${fiiMap[d]}`)
    .join('\n');

  const diiArms = allDates
    .filter(d => diiMap[d] !== undefined)
    .map(d => `    "${d}" => ${diiMap[d]}`)
    .join('\n');

  // Modernized Pine Script template output engine
  const pine = `//@version=5
indicator("FII & DII Flow", overlay=false, max_bars_back=500)

// Auto-generated by fetch.js — do not edit manually
// Last updated: ${new Date().toISOString().split('T')[0]}

// ── IMPORT YOUR 2026 DATA LIBRARY ──
import nithinshenoy7/FII_DII_Data_2026/1 as data2026

show_fii = input.bool(true, "Show FII", group="Display Toggles")
show_dii = input.bool(true, "Show DII", group="Display Toggles")
show_net = input.bool(true, "Show Net (FII + DII)", group="Display Toggles")

// 1. Generate date formats for both tracking types
d = str.format("{0,date,yyyy-MM-dd}", time)
int currentDateInt = year(time) * 10000 + month(time) * 100 + dayofmonth(time)

// 2. Dynamic Local Block (GitHub appends new lines directly inside here)
local_fii = switch d
${fiiArms}
    => float(na)

local_dii = switch d
${diiArms}
    => float(na)

// 3. Fallback Priority Calculation
fii_val = not na(local_fii) ? local_fii : data2026.getFII(currentDateInt)
dii_val = not na(local_dii) ? local_dii : data2026.getDII(currentDateInt)

// 4. Analysis and Visualisation Calculations (FIXED: Subtraction changed to Addition)
float net_val = (not na(fii_val) and not na(dii_val)) ? fii_val + dii_val : float(na)
color net_col = not na(net_val) and net_val >= 0 ? color.new(color.blue, 15) : color.new(color.maroon, 15)

fii_col = not na(fii_val) and fii_val >= 0 ? color.new(color.green, 15) : color.new(color.red, 15)
dii_col = not na(dii_val) and dii_val >= 0 ? color.new(color.teal, 15)  : color.new(color.orange, 15)

plot(show_fii ? fii_val : na, style=plot.style_columns, color=fii_col, title="FII Net ₹Cr")
plot(show_dii ? dii_val : na, style=plot.style_columns, color=dii_col, title="DII Net ₹Cr")
plot(show_net ? net_val : na, style=plot.style_columns, color=net_col, title="Net (FII + DII)")
hline(0, "Zero", color=color.gray, linewidth=1)

// ── F/D Sell-Pressure Marker (latest bar only) ──
var label fLabel = na
var label dLabel = na

if barstate.islast and not na(fii_val) and not na(dii_val)
    float fii_sold = fii_val < 0 ? math.abs(fii_val) : 0.0
    float dii_sold = dii_val < 0 ? math.abs(dii_val) : 0.0
    bool fii_sold_more = fii_sold > dii_sold

    float baseY = math.min(math.min(fii_val, dii_val), nz(net_val, 0)) - 1000

    label.delete(fLabel)
    label.delete(dLabel)

    fLabel := label.new(bar_index, baseY, text="F",
     style=label.style_label_up, size=size.normal,
     color=color.new(fii_sold_more ? color.red : color.blue, 0),
     textcolor=color.white)

    dLabel := label.new(bar_index, baseY - 1200, text="D",
     style=label.style_label_up, size=size.normal,
     color=color.new(fii_sold_more ? color.blue : color.red, 0),
     textcolor=color.white)

// ── Dashboard Metrics Table ──
var table t = table.new(position.top_right, 2, 4, border_width=1)
if barstate.islast and not na(fii_val)
    table.cell(t, 0, 0, "Entity (Today)", bgcolor=color.gray, text_color=color.white, text_size=size.small)
    table.cell(t, 1, 0, "Net ₹Cr",        bgcolor=color.gray, text_color=color.white, text_size=size.small)
    table.cell(t, 0, 1, "FII",            bgcolor=fii_col,    text_color=color.white, text_size=size.small)
    table.cell(t, 1, 1, str.tostring(fii_val, "#,###.##"), bgcolor=fii_col, text_color=color.white, text_size=size.small)
    table.cell(t, 0, 2, "DII",            bgcolor=dii_col,    text_color=color.white, text_size=size.small)
    table.cell(t, 1, 2, str.tostring(dii_val, "#,###.##"), bgcolor=dii_col, text_color=color.white, text_size=size.small)
    table.cell(t, 0, 3, "Net (F+D)",      bgcolor=net_col,    text_color=color.white, text_size=size.small)
    table.cell(t, 1, 3, str.tostring(net_val, "#,###.##"), bgcolor=net_col, text_color=color.white, text_size=size.small)
`;

  fs.writeFileSync('fii_dii.pine', pine);
  console.log(`✅ fii_dii.pine generated with ${allDates.length} trading days`);
}

async function main() {
  console.log('Trying NSE direct...');
  const res = await get('https://www.nseindia.com/api/fiidiiTradeReact', {
    'Referer': 'https://www.nseindia.com/',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-origin'
  });

  console.log('Status:', res.status);
  const data = JSON.parse(res.body);

  const fiiEntry = data.find(d => d.category === 'FII/FPI');
  const diiEntry = data.find(d => d.category === 'DII');

  const fii = parseFloat(String(fiiEntry.netValue).replace(/,/g, ''));
  const dii = parseFloat(String(diiEntry.netValue).replace(/,/g, ''));

  console.log(`✅ FII: ₹${fii} Cr | DII: ₹${dii} Cr`);

  updateCSV('data/FII_NET/data.csv', fii);
  updateCSV('data/DII_NET/data.csv', dii);

  generatePineScript();
}

main().catch(e => { console.error('❌ Fatal:', e.message); process.exit(1); });
